---
title: "LBC"
output: html_document
---

##Packages

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
install.packages("hexbin")
install.packages("hablar")
library(hablar)
install.packages("wesanderson")
library(wesanderson)


```

## R Markdown

Text

```{r lbc}

#Load data

lille_20_m_16022021 <- read.csv(file = "lille_20km_maisons_16022021.csv")

lille_20_m_16022021

#Calcul par commune

nb_biens_commune <- lille_20_m_16022021 %>%
  group_by(nom.commune) %>%
  summarise(mean(prix_m2),
            mean(surface_all),
            mean(prix),
            nombre = n()) %>%
  ungroup()

#Filtre commmunes + de 20 annonces

nb_biens_commune_clear <- nb_biens_commune %>%
  filter(nombre >19)
  
nb_biens_commune_clear  

#Rename des colonnes et sélection

nb_biens_commune_clear_mut <- nb_biens_commune_clear %>%
  mutate(prix_m2 = `mean(prix_m2)`,
         surface = `mean(surface_all)`) %>%
  select(nom.commune, prix_m2, nombre, surface) %>%
  arrange(desc(prix_m2))

nb_biens_commune_clear_mut

write.csv(nb_biens_commune_clear_mut, "prixm2_lille_20km_16022021.csv")

#Transfo en integer

class(nb_biens_commune_clear_mut$prix_m2)
  

##Graphique prix 

#Nuage de points (raw)

np1 <- ggplot(data = lille_20_m_16022021) +
  aes(x = surface_all, y = prix) +
  scale_x_continuous(trans = 'log2') +
  scale_y_continuous(trans = 'log2')+
  geom_point() 

#Smooth (raw)

smooth1 <- ggplot(data = lille_20_m_16022021) +
  aes(x = surface_all, y = prix)+
  geom_smooth()

smooth1 

#Par commune

prixm2_com <- ggplot(data = nb_biens_commune_clear_mut)+
  aes(x = nom.commune, y = prix_m2, fill = prix_m2) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  geom_col()
  

prixm2_com

#reorder graph

data_ordered <- read_csv(file = "prixm2_lille_20km_16022021.csv")

head(data_ordered)

prixm2_com2 <- ggplot(data = data_ordered)+
  aes(x = reorder(nom.commune, - prix_m2), y = prix_m2, fill = prix_m2) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  geom_col()+
  xlab("commune")+
  ylab("prix moyen au mètre carré")

prixm2_com2


```
