---
title: "scrap_lbc_lille"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval = FALSE, include = FALSE)
r = getOption("repos")
r["CRAN"] = "http://cran.us.r-project.org"
options(repos = r)

##Install Packages

install.packages("dplyr")
library(dplyr)
library(tidyverse)
install.packages("questionr")
library(questionr)
install.packages("cartography")
library(cartography)
library(sf)
install.packages("lwgeom")
library(lwgeom)
install.packages("SpatialPosition")
library(SpatialPosition)
install.packages("leaflet")
library(leaflet)
install.packages("maps")
library(maps)
install.packages("sp")
library(sp)
install.packages("geojsonio")
library(geojsonio)
install.packages("AddPolygons")
install.packages("rgdal")
library(rgdal)

```

## R Markdown


```{r}

#Ventes (décomposition des étapes, à optimiser).

##Chargement des données

lille_20_m_16022021 <- read.csv(file = "lille_20km_maisons_16022021.csv")

##Groupement par commune

nb_biens_commune <- lille_20_m_16022021 %>%
  group_by(nom.commune) %>%
  summarise(mean(prix_m2),
            mean(surface_all),
            mean(prix),
            nombre = n()) %>%
  ungroup()

##Filtre des commmunes avec plus de 20 annonces

nb_biens_commune_clear <- nb_biens_commune %>%
  filter(nombre >19)
  

##Rename des colonnes et sélection

nb_biens_commune_clear_mut <- nb_biens_commune_clear %>%
  mutate(prix_m2 = `mean(prix_m2)`,
         surface = `mean(surface_all)`) %>%
  select(nom.commune, prix_m2, nombre, surface) %>%
  arrange(desc(prix_m2))


write.csv(nb_biens_commune_clear_mut, "prixm2_lille_20km_16022021.csv")


##Graphique prix 

###Nuage de points (raw)

np1 <- ggplot(data = lille_20_m_16022021) +
  aes(x = surface_all, y = prix) +
  scale_x_continuous(trans = 'log2') +
  scale_y_continuous(trans = 'log2')+
  geom_point() 

###Smooth (raw)

smooth1 <- ggplot(data = lille_20_m_16022021) +
  aes(x = surface_all, y = prix)+
  geom_smooth()

smooth1 

###Par commune

prixm2_com <- ggplot(data = nb_biens_commune_clear_mut)+
  aes(x = nom.commune, y = prix_m2, fill = prix_m2) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  geom_col()
  

prixm2_com

###Reorder graph

data_ordered <- read_csv(file = "prixm2_lille_20km_16022021.csv")

head(data_ordered)

prixm2_com2 <- ggplot(data = data_ordered)+
  aes(x = reorder(nom.commune, - prix_m2), y = prix_m2, fill = prix_m2) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  geom_col()+
  xlab("commune")+
  ylab("prix moyen au mètre carré")

prixm2_com2


#Locations

##Chargement données

nordloc <- read.csv(file = "nord_locations_16022021.csv")

nordloccom <- nordloc %>% 
  group_by(commune) %>%
  summarise(mean(prix_m2),
            mean(surface_all),
            mean(prix),
            nombre = n()) %>%
  ungroup() %>%
  filter(nombre>10) %>%
  filter(commune != "") %>%
  mutate(prix_m2 = `mean(prix_m2)`,
         surface = `mean(surface_all)`)

nordloccom

##Visualisation locations par communes

prixm2locnord <- ggplot(data = nordloccom)+
  aes(x = reorder(commune, - prix_m2), y = prix_m2, fill = prix_m2) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  geom_col()+
  xlab("commune")+
  ylab("prix moyen au mètre carré")

prixm2locnord


##Jointure géo

###chargement geom

contours_com_nord <- read.csv2(file = "contours_communes_nord.csv")

contours_com_nord <- contours_com_nord %>%
  mutate(commune = Nom.de.la.commune) %>%
  select(commune, Geo.Shape, population_totale, Nom.du.département)

###traitements jointure
####clean text dans workbench (remove spaces)

locnordgeo <- read.csv(file = "locnord_geo.csv")

locnordgeo_com <- locnordgeo %>% 
  group_by(commune) %>%
  summarise(mean(prix_m2),
            mean(surface_all),
            mean(prix),
            nombre = n()) %>%
  ungroup() %>%
  filter(nombre>10) %>%
  filter(commune != "") %>%
  mutate(prix_m2 = `mean(prix_m2)`,
         nom_com = commune,
         surface = `mean(surface_all)`)

locnordgeo_com <- locnordgeo_com %>%
  inner_join(contours_com_nord, by ="commune")

write.csv(locnordgeo_com, "locnordgeo_com.csv")

###Dataviz carto

nordshp <- st_read("contours-geographiques-simplifies-des-communes-2019/")

plot(st_geometry(nordshp))

###Merge SHP avec data

mergecom <- merge(x = nordshp, y = locnordgeo_com, by = "nom_com")

###Tests

test6 <- choroLayer(x = mergecom, var = "prix_m2")
  
  
```
